---
- name: deploy java-app in AWS EC2
  hosts: local
  become: true
  tasks:
  - name: Creating EC2 Instances
    ec2:
      key_name: my-key1
      region: us-east-2
      instance_type: t2.micro
      image_id: ami-1234567890
      network:
        assign_public_ip: true
        security_group: default
        vpc_subnet_id: subnet-0123456      
      count: 2
      wait: true
    register: ec2

  - name: Add build and deploy instances to host group
    add_host:
      hostname: "{{ item.public_ip }}"
      groups: launched
    with_items: "{{ ec2.tagged_instances }}"

  - name: Install and configure software
    hosts: all
    become: true
    tasks:
      - name: Install git
        package:
          name: git
          state: present
      - name: Install java11
        package:
          name: openjdk-11-jdk
          state: present
      - name: Install maven
        package:
          name: maven
          state: present
      - name: Install tomcat
        package:
          name: tomcat9
          state: present
  
  - name: group "build" - make the artifact
  hosts: build
  become: true
  tasks:
  - name: Clone from Git repo
    git:
      repo: 'https://github.com/boxfuse/boxfuse-sample-java-war-hello.git'
      dest: /tmp/boxfuse-sample-java-war-hello

  - name: Build Java project with Maven
      shell: mvn package
      args:
        chdir: /tmp/boxfuse-sample-java-war-hello

  - name: group "build" - copy artifact to "prod" server
    hosts: build
    become: true
    tasks:
    - name: copy app to prod server (aws) 
      shell: rsync -avz /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war root@<prod_ip>:/usr/local/tomcat/webapps/

  - name: Start and Enable Tomcat 10 on sever
    hosts: prod
    systemd:
      name: tomcat
      state: started
      daemon_reload: true
